import { Outfit, Ovo } from 'next/font/google';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});
const ovo = Ovo({
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata = {
  title: 'Portfolio - Blessed Zinaka',
  description: 'Generated by Blessed Zinaka',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='scroll-smooth dark'>
      <body
        className={`${outfit.className} ${ovo.className} antialiased leading-8 overflow-x-hidden dark:bg-dark dark:text-light`}
      >
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
